### ISSUE TITLE
Last page shown in breadcrumb when back function of browser is used

### ISSUE THREAD

**Issue by SPampel** [digiapulssi/grafana-breadcrumb-panel#14]
Hi,
first of all: thank you very much for the plugin!

The only issue I have is that if I click a link to "dashboard 2" in a text panel on "dashboard 1" do go down in my hierarchy of dashboards and then use the browsers' back function, the breadcrumb shows "dashboard 1" -> "dashboard 2". I expect it to only show "dashboard 1".

Browser: Version 61.0.3163.91 (Developer Build) (64-bit) on Arch Linux

best regards,
Stephan

**Comment by timyllym** [comment]
Hi, Thanks for your message. I'll check this and get back to you.

**Comment by kompa3** [comment]
@timyllym , is this same as the bug reported as an internal ticket PULSSI-865?

**Comment by timyllym** [comment]
@kompa3, yes it should be. I'll check the changes to public version.

**Comment by timyllym** [comment]
@SPampel , this should be now fixed. I'm waiting still that update gets to Grafana plugin repository.

**Comment by timyllym** [comment]
Updated version is now in Grafana plugin repository.

**Comment by SPampel** [comment]
@timyllym I tested the version from the Grafana plugin repository - work like charm. Thank you very much!
