### ISSUE TITLE
Auto referesh is changed when hopping back to a previous panel.

### ISSUE THREAD

**Issue by HactarofDoom** [digiapulssi/grafana-breadcrumb-panel#15]
Scenario: 

Main dashboard (overview with drilldown links to detail dashboards, all with Breadcrumb on the very top for ease of navigation back to previous panels) on a 15min refresh. Click a drilldown link taking you to a detail dashboard that is on a 30sec refresh (detail dashboard opend in the same window not in a new tab).

If you now go back to the main dashboard via Breadcrumb the main dashboard is on a 30sec refresh like the detail dashboard.

Since our main dashboard has quite a lot of stats to display the 30sec. refresh is very counter productive, would be nice if this could be fixed. I would guess it is "just" the refresh argument in the URL that is taken from the panel you are on not the panel you want to go back too.

**Comment by kompa3** [comment]
Created an internal bug ticket https://jira.digia.com/browse/PULSSI-1019 out of this, @timyllym  this may be related to other bugs in the current sprint?

**Comment by timyllym** [comment]
Yes, it sounds like the same issue I'm working on. I'll check it.

**Comment by timyllym** [comment]
@HactarofDoom , this should be now fixed. I'm waiting still that update gets to Grafana plugin repository.

**Comment by HactarofDoom** [comment]
Perfect, thanks a lot for the quick response to this!

**Comment by timyllym** [comment]
Updated version is now in Grafana plugin repository.
