### ISSUE TITLE
Does it work in grafana 4.7.x

### ISSUE THREAD

**Issue by botzill** [digiapulssi/grafana-breadcrumb-panel#16]
I installed the plugin via CLI in grafana ``Version 4.7.0-pre1 (commit: 03c23dd)`` but I don't see any changes, there are no breadcrumbs. Does it support this version?

Thx!

**Comment by timyllym** [comment]
Hi, yes it should. I just tried installing the latest nightly 4.7.0-pre1 and installing digiapulssi-breadcrumb-panel via grafana-cli. Then just add the breadcrumb panel to each dashboard where you want it visible.

**Comment by botzill** [comment]
Thx @timyllym it works now when adding new dashboard. How about when we have a list of dashboards files and upload them so that grafana loads from disk, seem that not works in this case, at least I see empty result, is it required for dashboard to be in DB?

**Comment by timyllym** [comment]
I'm not sure if I completely understand how you are using Grafana. Are you loading dashboards from a different place than Grafana server? Anyway, the url handling is currently made so that it expects all dashboards locating under db.

**Comment by botzill** [comment]
Yes, I load dashboards from folder on Grafana startup and my url looks like `/dashboard/file/overview_app_logs.json` but seems that it require them to be in DB.

**Comment by timyllym** [comment]
This is now fixed in latest version and will be updated to Grafana plugin repository shortly.
