### ISSUE TITLE
Breadcrumbs override variables passed from other dashboards

### ISSUE THREAD

**Issue by calebtote** [digiapulssi/grafana-breadcrumb-panel#21]
Hey, love the plugin! We've hit a bit of an issue though - when we pass parameters from another dashboard, the page refreshes with the breadcrumbs and removes the existing variables. 

## Repro

- Create _Dashboard-A_, with a graph and breadcrumbs
-- Click the graph drop down, and select `View`
-- Take note of the `panelID` in the URL
- Create _Dashboard-B_, with a single-stat graph and breadcrumbs
-- Under **General**, add a `Drilldown link`
-- Specify _Dashboard-A_
-- For the Url params, add `panelId=1&fullscreen`
-- Save and test the link

## What happens
The page loads the full screen panel, followed by a refresh with the variables stripped out and replaced with the breadcrumbs

## What I expected
The page loads the full screen panel and doesn't refresh to show breadcrumbs

**Comment by calebtote** [comment]
Quick update, looks like it overrides all variables not just variables passed in from a previous dashboard.

**Comment by timyllym** [comment]
Hi, that seems to be the case. I'll check it and get back to you.

**Comment by calebtote** [comment]
#22 fixes this partially, but for some reason `fullscreen` is still removed when the panel loads (taking me back to the full dashboard and closing the fullscreen panel)

**Comment by timyllym** [comment]
I found out that the way I was changing search query variables rewrote the all variables. Now it changes only breadcrumb. It will take some time for this fix to appear in Grafana plugin repository.

**Comment by calebtote** [comment]
Built your source changes and tested locally -- this looks fixed. Thanks for the super quick turn around!
