### ISSUE TITLE
how to change color of text in breadcrumb

### ISSUE THREAD

**Issue by sabagour** [digiapulssi/grafana-breadcrumb-panel#28]
Hi,
I want to set the color of the breadcrumb text to blue. However I do not see any option to do it.

Can you please help.

Thanks.

**Comment by timyllym** [comment]
Hi, 
Breadcrumb uses Grafana's default text color for dark and light theme. There is currently no option to change the text color and no plans to add such feature. If you have some panel of your own you can add CSS classes to Grafana which could change the text color. You'd need to add color definition to class breadcrumb-container.

e.g.
.breadcrumb-container {
  color: #ff0000;
}
