### ISSUE TITLE
breadcrumb not working correctly with back button

### ISSUE THREAD

**Issue by sabagour** [digiapulssi/grafana-breadcrumb-panel#29]
Hi,
The breadcrumb is working fine for a normal navigation.
For example navigate through,
DashA -> DashB -> DashC -> DashD
When I use the back button of the browser all the way till Dash A it is working fine.
DashD back DashC back DashB back DashA ----- works fine

However, for DashA -> DashB -> DashC -> DashD
if I click on DashD twice (even though I am on DashD) and then use the back button of the browser then it does not work correctly. 
I see below error on console -
Uncaught TypeError: Cannot read property 'breadcrumb' of null
// Listen for PopState events so we know when user navigates back with browser
                    // On back navigation we'll take the changed breadcrumb param from url query and
                    // recreate dashboard list
                    window.onpopstate = function (event) {
                        if (_this.dashboardList.length > 0) {
                            if ($location.state().breadcrumb) {
                                var _items = $location.state().breadcrumb.split(",");
                                _this.createDashboardList(_items);
                            }
                        }
                    };

Please help. 
Thank you!

**Comment by timyllym** [comment]
Hi,
Yes, there seems to be some kind of incompatibility with this panel and the latest version of Grafana. I made a fix for this and it is waiting for Grafana approval.

**Comment by sabagour** [comment]
Thank you!

**Comment by timyllym** [comment]
New version is now in available Grafana plugin repository.
