### ISSUE TITLE
[Feature Request] Disable Text in root Dashboard

### ISSUE THREAD

**Issue by florianwgnr** [digiapulssi/grafana-breadcrumb-panel#30]
Feature:

It would be great to choose if the panels text is enabled or disabled (on a specific dashboard), so the panel could become transparent.

Why?

On root dashboards or landing pages sometimes the heading is a big, centered colorful text field. But still breadcrumb must be there so set it as root dashboard, so there is a second "headline".
Instead of making breadcrumb to fit everybodys style idea, just integrate an option to make the panel transparent. 

![grafik](https://user-images.githubusercontent.com/39341393/61778976-283f9780-ae00-11e9-8cd3-58f0cb50aec5.png)

**Comment by timyllym** [comment]
Added posibility hide text. New version Grafana plugin repository.
