### ISSUE TITLE
[FR] limiting amount of tracked dashboards

### ISSUE THREAD

**Issue by adivinho** [digiapulssi/grafana-breadcrumb-panel#31]
IMHO it would be useful to limiting amount of shown dashboards to last X. Now panel size has to be big enough in order to omit partly shown text. But most of the time it's just empty unused space.

![Screenshot_20190828_193149](https://user-images.githubusercontent.com/25184101/63874813-dffd3180-c9ca-11e9-9195-045747a36f30.png)

**Comment by timyllym** [comment]
Support added for setting the max amount of items in options tab. Defaults to 25 items. Version updated in Grafana plugin repository.
