### ISSUE TITLE
Grafana 6.x

### ISSUE THREAD

**Issue by imilyukov** [digiapulssi/grafana-breadcrumb-panel#32]
Does it work with Grafana 6.x. If it isn't, are you planning to improve compatibility?
Thanks,

**Comment by gkpraveen1988** [comment]
Hi, Just tried to use the plugin on Grafana  v6.4.1. I was able to install the plugin without any trouble. and when I configured, the top panel title is overlapping with the content. Your extended help would be highly appreciated. Thank you.

**Comment by timyllym** [comment]
@gkpraveen1988: Can you add a screenshot? The panel title shouldn't be overlapping the content. And yes, this panel should work on Grafana 6.

**Comment by gkpraveen1988** [comment]
Thank you for your response. Here is the screenshot
![Screenshot](https://user-images.githubusercontent.com/6847782/66366488-2b8bfd80-e9c3-11e9-89a8-bf4f84cb98c0.jpg)

**Comment by timyllym** [comment]
Grafana 6 seems to subtract the panel title area if no panel title is set. If you set one spacebar char as the title then the title area stays in the top. This is the same behavior with all panels in Grafana 6.

**Comment by timyllym** [comment]
I updated the version in Grafana plugin repository. There are no fixes however to the issue with the panel title area as it is Grafana 6 feature.
