### ISSUE TITLE
How does this work

### ISSUE THREAD

**Issue by reuvygroovy** [digiapulssi/grafana-breadcrumb-panel#33]
Hi
I imported the plugin but I can't seem to see how it works and/or what it does. Can you send me a few screenshots?

**Comment by timyllym** [comment]
Hi, if you add breadcrumb panel to all of your dashboards then it shows your navigation history within those dashboards in one browser session. It can track only those dashboards that have the breadcrumb panel.

![breadcrumb_screenshot](https://user-images.githubusercontent.com/13029109/74409803-2a228400-4e40-11ea-95e3-2924e97619b8.png)
