### ISSUE TITLE
Grafana 8.x??

### ISSUE THREAD

**Issue by gopalk20** [digiapulssi/grafana-breadcrumb-panel#35]
Does it work with Grafana 8.x.

I have used Grafana 7.2 version with Breadcrum panel, that time it was working, but after upgrade to 8.4.1, I am getting errror
![image](https://user-images.githubusercontent.com/22351939/155267809-95ab6a91-a2e5-4d00-98f4-825eba497a08.png)

I have checked the plugin installed in my system. It was installed
![image](https://user-images.githubusercontent.com/22351939/155267880-24671469-0c02-450e-851e-9ac5be4c8af2.png)

Do I missed any settings or this plugin will not support latest version??

**Comment by MariusBrill** [comment]
Same for me when installing the plugin by unzipping the project into the plugin path.

**Comment by timyllym** [comment]
I have migrated this panel to React to support latest Grafana version. That is however a new panel this old panel is deprecated. The new panel can be found with id timomyl-breadcrumb-panel https://grafana.com/grafana/plugins/timomyl-breadcrumb-panel/ So closing this issue now.
