### ISSUE TITLE
Migrate from Angular 1 to latest React 

### ISSUE THREAD

**Issue by atymchuk** [digiapulssi/grafana-breadcrumb-panel#36]
Hey!

Grafana announced they will [drop support for Angular 1](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) in June 2022, which is quite soon. Do you guys plan on migrating it to React anytime soon? Something already underway?

**Comment by timyllym** [comment]
Hi, no plans yet. I'll try to migrate to React before summer.

**Comment by timyllym** [comment]
I have migrated this panel to React to support latest Grafana version. That is however a new panel this old panel is deprecated. The new panel can be found with id timomyl-breadcrumb-panel https://grafana.com/grafana/plugins/timomyl-breadcrumb-panel/ So closing this issue now.
